---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: Install ubuntu apt-key server
  apt_key:
    id=A2923DFF56EDA6E76E55E492D3A80E30382E94DE
    keyserver=hkp://keyserver.ubuntu.com:80
    state=present
  when: datadog_apt_key_url_new is not defined
  become: yes

- name: Install Datadog apt-key
  apt_key:
    id=A2923DFF56EDA6E76E55E492D3A80E30382E94DE
    url={{ datadog_apt_key_url_new }}
    state=present
  when: datadog_apt_key_url_new is defined
  become: yes

- name: Ensure ubuntu apt-key server is present
  apt_key:
    id=C7A7DA52
    keyserver=hkp://keyserver.ubuntu.com:80
    state=present
  when: datadog_apt_key_url is not defined
  become: yes

- name: Ensure Datadog apt-key is present
  apt_key:
    id=C7A7DA52
    url={{ datadog_apt_key_url }}
    state=present
  when: datadog_apt_key_url is defined
  become: yes

- name: Ensure Datadog repository is up-to-date
  apt_repository:
    repo: '{{ datadog_apt_repo }}'
    state: present
    update_cache: yes
  become: yes

- name: Ensure pinned version of Datadog agent is installed
  apt:
    name: datadog-agent={{ datadog_agent_version }}
    state: present
    force: "{{ datadog_agent_allow_downgrade }}"
  environment:
    DD_INSTALL_ONLY: "{{ datadog_agent_install_only }}"
  when: datadog_agent_version != ""
  become: yes

- name: Ensure Datadog agent is installed
  apt:
    name: datadog-agent
    state: latest
  environment:
    DD_INSTALL_ONLY: "{{ datadog_agent_install_only }}"
  when: datadog_agent_version == ""
  become: yes
